[general]
	import = [
		"~/.config/alacritty/catppuccin-mocha.toml"
	]

[terminal]
	shell = "/bin/zsh"

[window]
	dynamic_title = false
	dynamic_padding = true
	resize_increments = true

[font]
	normal = { family = "Hack Nerd Font", style = "Regular" }
	bold = { family = "Hack Nerd Font", style = "Bold" }
	italic = { family = "Hack Nerd Font", style = "Italic" }
	bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
	size = 14
	offset = { x = 1, y = 0 }
	builtin_box_drawing = false # alacritty's built-in box drawing draws less promiment characters

[cursor]
	thickness = 0.25
	blink_timeout = 0
